apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: tejo-nails
data:
  NODE_ENV: "production"
  PORT: "3001"
  FRONTEND_URL: "https://138.199.226.201"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: tejo-nails
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi90ZWpvX25haWxzX3BsYXRmb3JtP3NjaGVtYT1wdWJsaWM= # base64 encoded DATABASE_URL
  REDIS_URL: cmVkaXM6Ly86cmVkaXMxMjNAcmVkaXMtc2VydmljZTo2Mzc5 # base64 encoded REDIS_URL
  JWT_SECRET: cHJvZHVjdGlvbi1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtdGhpcw== # base64 encoded JWT secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tejo-nails
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tejo-nails/backend:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/system-health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/system-health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: uploads-storage
              mountPath: /app/uploads
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: uploads-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: tejo-nails
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: tejo-nails
spec:
  selector:
    app: backend
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: tejo-nails
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
